version: "3.7"
services:
  main: 
    build:
      context: .
    env_file: 
      - .env
    volumes: 
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    command: npm run start
    depends_on:
      - postgres
    restart: always
  postgres:
    image: postgres:latest
    env_file: 
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: weather
    ports:
      - 5432:5432
    restart: always
